# Generated by Django 3.0.2 on 2020-02-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_auto_20200215_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.Users'),
        ),
    ]
