# Generated by Django 3.0.2 on 2020-02-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_auto_20200215_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reserve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.Reserve'),
        ),
    ]
